### ISSUE TITLE
pipUtils1.0.py", line 46, in getpackage     str2 = strsplit[1] IndexError: list index out of range

### ISSUE THREAD

**Issue by mokaki** [cuntou0906/pipUtils#1]
您好
如用您範本一切正常
但轉 Pack.py 後
出現錯誤

Traceback (most recent call last):
  File "C:\Users\mokaki\Desktop\autoweb21\py\hhh\pipUtils1.0.py", line 78, in <module>
    PackageName = getpackage(path,lines)
  File "C:\Users\mokaki\Desktop\autoweb21\py\hhh\pipUtils1.0.py", line 46, in getpackage
    str2 = strsplit[1]
IndexError: list index out of range

---

Pack.py

#!usr/bin/env python
#-*- coding:utf-8 _*-
"""
mokaki
202107142035
https://github.com/cuntou0906/pipUtils

"""

import      os
import      hashlib
import      binascii
from      selenium      import      webdriver
from      selenium.webdriver.chrome.options      import      Options
from      selenium.webdriver.support.ui      import      WebDriverWait
from      selenium.webdriver.support.wait      import      WebDriverWait
from      selenium.webdriver.support      import      expected_conditions      as      EC
from      selenium.webdriver.common.by      import      By
from      selenium.webdriver.common.keys      import      Keys
from      fake_useragent      import      UserAgent
import      time
import      datetime
import      re
import      random
import      requests
import      urllib
import      sys
import      urllib.request
from      urllib.request      import      urlretrieve
from      PyClassicRound      import      classic_round
import      rarfile
import      io
from      PIL      import      Image
from      threading      import      *
from      fontTools.ttLib      import      TTFont
from      tkinter      import      *
from      functools      import      partial
import      json
from      pprint      import      pprint
from      urllib.request      import      urlopen

---

謝謝您

**Comment by mokaki** [comment]
已解決
問題在
pipUtils1.0.py 77
#lines = [9,13]                                         # import语句所在的行
lines = [10,24]
-----
Pack.py 轉後行數找不到
謝謝
